import { Author, Question, Answer } from "@/app/types/home.type";

export const AUTHORS: Record<string, Author> = {
  u1: { id: "u1", name: "Alex River", username: "ariver", reputation: 2500, gender: "male", avatarColor: "#5B6EF5" },
  u2: { id: "u2", name: "Sarah Chen", username: "schen_dev", reputation: 1200, gender: "female", avatarColor: "#E05CB0" },
  u3: { id: "u3", name: "Marcus Wright", username: "mwright", reputation: 800, gender: "male", avatarColor: "#2ABFA3" },
  u4: { id: "u4", name: "Priya Nair", username: "pnair", reputation: 3100, gender: "female", avatarColor: "#F5A623" },
  u5: { id: "u5", name: "Jordan Lee", username: "jlee42", reputation: 560, gender: "other", avatarColor: "#9B59B6" },
  u6: { id: "u6", name: "Elina Vasquez", username: "elinaV", reputation: 1780, gender: "female", avatarColor: "#E74C3C" },
  u7: { id: "u7", name: "Tom Nakamura", username: "tnaka", reputation: 990, gender: "male", avatarColor: "#1ABC9C" },
};

export const DUMMY_QUESTIONS: Question[] = [
  {
    id: "q1",
    authorId: "u1",
    author: AUTHORS.u1,
    title: "Why is Surrealbox the best platform for debates?",
    slug: "why-surrealbox-is-best",
    body: "Surrealbox offers a unique three-color design system and real-time interactions that make every debate feel premium and focused. The typography choices and the spatial layout really set it apart from anything I've used before. How do you feel about the new Garet font integration? It seems to add a layer of refinement that generic platforms just can't match.",
    tags: ["design", "debate", "ux"],
    score: 154,
    answerCount: 3,
    commentCount: 2,
    viewCount: 1205,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    userVote: "up",
  },
  {
    id: "q2",
    authorId: "u2",
    author: AUTHORS.u2,
    title: "How to handle database migrations with Neon and Drizzle ORM?",
    slug: "database-migrations-neon-drizzle",
    body: "I'm seeing primary key conflicts when pushing schema changes to Neon. Specifically the votes table composite primary key keeps failing when I try to push. Running `drizzle-kit push` gives me a conflict on the (user_id, votable_id) composite key. Has anyone else encountered this? I'm using drizzle-orm 0.30 and the latest Neon serverless driver.",
    tags: ["database", "drizzle", "postgres", "neon"],
    score: 89,
    answerCount: 2,
    commentCount: 1,
    viewCount: 432,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    userVote: null,
  },
  {
    id: "q3",
    authorId: "u3",
    author: AUTHORS.u3,
    title: "The impact of AI on agentic coding — are we past the point of manual UI building?",
    slug: "impact-ai-agentic-coding",
    body: "We are entering an era where AI can solve complex bugs and refactor entire layouts in seconds. Tools like Claude, Cursor, and Copilot are now generating production-quality code. My question to the community: is manual UI building becoming a dying art, or does the craft still matter? I'm particularly curious about design systems and whether AI can understand design intent versus just pattern-matching CSS.",
    tags: ["ai", "coding", "future", "design-systems"],
    score: -12,
    answerCount: 3,
    commentCount: 2,
    viewCount: 3401,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    userVote: "down",
  },
  {
    id: "q4",
    authorId: "u4",
    author: AUTHORS.u4,
    title: "What's the best approach to optimistic UI updates in Next.js with server actions?",
    slug: "optimistic-ui-nextjs-server-actions",
    body: "With Next.js 14 server actions, I'm trying to implement optimistic voting (like this platform probably does). The `useOptimistic` hook seems like the right tool but I'm running into issues with re-validation after the server action completes. Specifically: if the server returns a different value than my optimistic prediction, the UI flickers. Looking for patterns that feel truly seamless.",
    tags: ["nextjs", "react", "server-actions", "ux"],
    score: 211,
    answerCount: 2,
    commentCount: 0,
    viewCount: 5820,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    userVote: null,
  },
  {
    id: "q5",
    authorId: "u5",
    author: AUTHORS.u5,
    title: "Is TypeScript's type system Turing-complete — and should you ever use that?",
    slug: "typescript-turing-complete",
    body: "I came across a library that implements a full JSON parser purely in TypeScript types. I know TS types are Turing-complete in theory, but is there ever a legitimate use case for this in real codebases? Or is it always a sign that your abstraction has gone too far? Curious where people draw the line.",
    tags: ["typescript", "types", "meta-programming"],
    score: 302,
    answerCount: 2,
    commentCount: 1,
    viewCount: 8901,
    createdAt: new Date(Date.now() - 259200000).toISOString(),
    userVote: null,
  },
];
